version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://username:postgres@api:5432/socialnetwork
      DB_HOST: api
      DB_USER: postgres
      DB_PASS: 123456
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  frontend:
    build:
      context: ./client
    ports:
      - "3001:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
